# Makefile for COMP1921 Week 04 Lab

noargs:
	@echo You must use \"make wfreq1\" or \"make wfreq2\"

wfreq1: wfreq.c
	gcc -Wall -g -o wfreq1 wfreq.c

wfreq2: wfreq.c
	gcc -Wall -pg -o wfreq2 wfreq.c

clean:
	rm -f wfreq1 wfreq2 gmon.out core
